// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk-9UbX8dlz1WGx3IceYLUZtGUz1UcPMI',
    appId: '1:1018638765044:web:d887b434af9688a1dec7a1',
    messagingSenderId: '1018638765044',
    projectId: 'drivendriver-3f9d9',
    authDomain: 'drivendriver-3f9d9.firebaseapp.com',
    storageBucket: 'drivendriver-3f9d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXEBLMK5UJEHJmeGvOIdOXaSYwcatWomk',
    appId: '1:1018638765044:android:474cff5a62d03771dec7a1',
    messagingSenderId: '1018638765044',
    projectId: 'drivendriver-3f9d9',
    storageBucket: 'drivendriver-3f9d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEWDLP2N0LIojNWmMWpDMbP2DmvxxcARg',
    appId: '1:1018638765044:ios:f5a69c85c6353f13dec7a1',
    messagingSenderId: '1018638765044',
    projectId: 'drivendriver-3f9d9',
    storageBucket: 'drivendriver-3f9d9.appspot.com',
    iosBundleId: 'com.example.drivenDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEWDLP2N0LIojNWmMWpDMbP2DmvxxcARg',
    appId: '1:1018638765044:ios:9bd5a3208ee9adc4dec7a1',
    messagingSenderId: '1018638765044',
    projectId: 'drivendriver-3f9d9',
    storageBucket: 'drivendriver-3f9d9.appspot.com',
    iosBundleId: 'com.example.drivenDriver.RunnerTests',
  );
}
